language: php
php:
  - 5.5
  - 5.6
  - hhvm
services:
  - memcached
before_script:
 - composer self-update
 - sudo apt-get update -qq
 - sudo apt-get install -qq zend-framework php5-memcached
 - mysql < db.dist/db.structure.travis.sql
 - yes | pecl install memcached
script: 
 - composer install
 - phpunit